services:
  dev:
    build:
      context: .
      target: dev
    image: localhost/vhdl-fmt-dev:latest
    volumes:
      - .:/app:z
      - conan-cache:/root/.conan2
    command: [ "/bin/bash" ] # explicit default

volumes:
  conan-cache:
