name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

jobs:
  dictionary:
    runs-on: ubuntu-latest
    name: Check if dictionary is sorted and all ignored words are used
    timeout-minutes: 1

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check if dictionary is sorted
        run: |
          BOLD_RED="\033[1;31m"
          BOLD_YELLOW="\033[1;33m"
          BOLD_GREEN="\033[1;32m"
          RESET="\033[0m"

          # Check if all ignored words are actually used
          bash .github/scripts/check-cspell-ignored.sh

          if [ ! -f ".cspell_ignored" ]; then
            echo -e "${BOLD_RED}Error: .cspell_ignored not found${RESET}"
            exit 1
          fi

          # Check if file is sorted (case-insensitive)
          if sort -cf .cspell_ignored; then
            echo -e "${BOLD_GREEN}✓ .cspell_ignored is properly sorted${RESET}"
          else
            echo -e "${BOLD_RED}Error: .cspell_ignored is not sorted alphabetically (case-insensitive)${RESET}"
            echo -e "${BOLD_YELLOW}To fix this, run: make sort-dictionary{RESET}"
            exit 1
          fi
        shell: bash

  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    timeout-minutes: 1

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Starting cspell
        uses: streetsidesoftware/cspell-action@v7
        with:
          files: ""
          root: "."
          check_dot_files: false
          inline: error
          treat_flagged_words_as_errors: false
          suggestions: true
          strict: true
          config: ".cspell.yaml"
          incremental_files_only: ${{ env.ACT != 'true' }}
          verbose: true
          use_cspell_files: false

  formatter:
    runs-on: ubuntu-latest
    name: Formatter Check
    timeout-minutes: 10
    container:
      image: archlinux:base-devel

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          install_gersemi: true

      - name: Check formatting
        run: |
          source .venv/bin/activate
          make check-format

  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 10
    container:
      image: archlinux:base-devel

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          install_conan: true

      - name: Setup Conan profile
        run: |
          source .venv/bin/activate
          conan profile detect --force

      - name: Build
        run: |
          source .venv/bin/activate
          make

  lint-header:
    runs-on: ubuntu-latest
    name: Lint Headers
    timeout-minutes: 10
    container:
      image: archlinux:base-devel

    needs: build
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          install_conan: true

      - name: Setup Conan profile
        run: |
          source .venv/bin/activate
          conan profile detect --force

      - name: Build
        run: |
          source .venv/bin/activate
          make

      - name: Run lint on headers
        run: |
          source .venv/bin/activate
          make lint LINT_FILES=header

  lint-sources:
    runs-on: ubuntu-latest
    name: Lint Sources
    timeout-minutes: 10
    container:
      image: archlinux:base-devel

    needs: build
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          install_conan: true

      - name: Setup Conan profile
        run: |
          source .venv/bin/activate
          conan profile detect --force

      - name: Build
        run: |
          source .venv/bin/activate
          make

      - name: Run lint on sources
        run: |
          source .venv/bin/activate
          make lint LINT_FILES=source

  test:
    runs-on: ubuntu-latest
    name: Test
    timeout-minutes: 10
    container:
      image: archlinux:base-devel

    needs: build
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          install_conan: true

      - name: Setup Conan profile
        run: |
          source .venv/bin/activate
          conan profile detect --force

      - name: Build
        run: |
          source .venv/bin/activate
          make

      - name: Run tests
        run: make test
